# Dockerfile.flask
FROM python:3.8

ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy app files
COPY . /app/

# Back-end Port
EXPOSE 80

# Run Flask app with Gunicorn
CMD ["gunicorn", "server:app", "--bind", "0.0.0.0:80"]