name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}

      - name: Add known hosts to establish VM connection
        run: ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        env:
          HOST: ${{ secrets.DROPLET_IP }}
        run: |
          ssh root@$HOST << EOF
            set -e
            cd NewsWebsite
            git pull origin main
            cd server
            docker compose pull
            docker compose up -d --build --remove-orphans
          EOF
